package com.java;

import java.util.Random;

// TODO SETUP THIS CLASS
public class UIConfig extends TestBase {
//And there is a UIConfig class that holds all the information and configurations for ui tests
//         *  - add a variable 'testId' that will be assigned with the randomly generated by a Random class. use: new Random().nextInt();
//         *  - add a variable 'configurations' with a value of "UI Test Configurations"
//         *  - override method 'initializeTestConfigurations'
//         *      * add a print line current 'configurations'
//         *      * add a print line message "Here I would add some cool UI configurations for browser"
//         *  - override method 'hashCode' that returns 'testId'
//         *  - override method 'toString' and return information details:
//         *      * new line for "app name: " and call getAppName()
//         *      * new line for "test id: " and get from 'testId' and add a message " is randomly generated in TestBase class"
//         *      * new line for "config: " and get from 'configurations'
//         *

    public int testId = new Random().nextInt();
    public String configurations = "UI Test Configurations";

    @Override
    public void initializeTestConfigurations() {
        System.out.println(configurations);
        System.out.println("Here I would add some cool UI configurations for browser");
    }

    @Override
    public int hashCode() {
        return testId;
    }

    @Override
    public String toString() {
        return "\n" + "app name: " + getAppName()
                + "\n" + "test id: " + testId + " is randomly generated in TestBase class"
                + "\n" + "config: " + configurations;

    }

    @Override
    public boolean equals(Object o) {
       // return this.toString().equals(o.toString());
        return this.hashCode()==o.hashCode();
    }

}